services:

  produto-api:
    build: .
    container_name: ms-produto-api-dev
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-produto:3307/produto_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: produto_user
      SPRING_DATASOURCE_PASSWORD: secure_password_produto
      SPRING_ENDERECO_BD: db-produto
    networks:
      - pedido-net

volumes:
  db_data_produto:

networks:
  pedido-net: